name: Update Stargazers Chart

on:
  schedule:
    - cron: "0 */6 * * *"  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - main

jobs:
  stargazers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: XiaojuCH
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          filename: github-metrics/stargazers.chartist.svg
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist
